# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: phpdocker/phpdocker:7.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ arch }}-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
      - run: composer install -n --prefer-dist --no-progress -o

      - save_cache:
          key: v1-dependencies-{{ arch }}-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      # run tests!
      - persist_to_workspace:
          root: .
          paths:
            - "vendor/*"
  build-image:
    docker:
      # specify the version you desire here
      - image: docker:git

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo ".git" >> .dockerignore
      - run: echo "$SERVICE_ACCOUNT_KEY" > keyfile.json
      - run: docker login -u _json_key --password-stdin https://eu.gcr.io < keyfile.json
      - run: docker build . -f Dockerfile -t $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
      - run: docker push $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - build-image:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /[0-9\-]/
